import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBarComponent from "@/components/layout/navbar/NavBarComponent";
import SessionWrapper from "./SeeionWrapper";
import NextUILayout from "./NextUIProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kang Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // add seesionWeapper 
    <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>
        <NextUILayout>
            <header>
               <NavBarComponent/>
            </header>  
            {children}
        </NextUILayout>
      </body>
    </html>
    </SessionWrapper>
  );
}
